### ISSUE TITLE
RSS feed only contains excerpts

### ISSUE THREAD

**Issue by mattwaler** [tailwindlabs/blog.tailwindcss.com#8]
Hey Tailwind team!

I absolutely love the new blog! 

I was wondering if you guys were going to be adding in an RSS feed, or possibly a newsletter so I don't need to manually check back every once in a while.

Keep doing great work!

**Comment by bradlc** [comment]
Hey @mattwaler, thanks! We have a feed here: https://blog.tailwindcss.com/feed.xml

**Comment by mattwaler** [comment]
Awesome! 

I didn't even know it existed, maybe it should be added in the header/footer for others who can't find it too?

**Comment by mattwaler** [comment]
Also, 

I'm not sure if you guys are aware of this, but it appears that the entirety of your blog posts are not making it into the RSS feed, only the excerpts are:

<img width="1500" alt="Screen Shot 2020-07-17 at 9 19 27 AM" src="https://user-images.githubusercontent.com/32300026/87790557-b9c4c800-c80e-11ea-93da-69e418eec9dc.png">

**Comment by deadcoder0904** [comment]
Would love RSS 👍
